### ISSUE TITLE
Create MSBuild comparison task

### ISSUE THREAD

**Issue by gh-devtility** [devtility/asmref-baseliner#11]
### Description
MSBuild task that compares two report files and reports an error if the set of references has changed.

Possible differences in the reports:
* differences in comments: these should be ignored.
* assemblies added
* assemblies removed
* referenced assembly version changed (to older or newer version)

Any non-comment difference should produce an error.

### TODO
- [x] create build task
- [x] create targets files
- [x] unit tests
- [x] targets tests (integration tests)
